AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
    - Rakefile
    - gruf-zipkin.gemspec

Lint/AmbiguousOperator:
  Enabled: false

Metrics/ParameterLists:
  Max: 20

Metrics/AbcSize:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - lib/bigcommerce/lightstep/redis/wrapper.rb

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
